site_name: Project Tracker
site_description: Track progress across multiple courses
site_author: Olivia Mikler

theme:
  name: material
  palette:
    scheme: slate
    primary: green
    accent: light green
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - content.code.annotate

nav:
  - Home: index.md
  - How to use: how_to_use.md
  - API: api.md


plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
